version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
branches:
  only:
  - master
os: Visual Studio 2015 RC
platform: x86
environment:
  COVERALLS_REPO_TOKEN:
    secure: /tRhFlxb1FuCndTTmE9TLmPhWL71TtQZOOnRPs8ut6cSVcK+p1GAN1ztJhIBIU6X
before_build:
  - nuget restore ".\MobilePosemetre.sln"	
build:
  project: MobilePosemetre.sln
  verbosity: minimal
