version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
branches:
  only:
  - master
os: Visual Studio 2015 RC
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: /tRhFlxb1FuCndTTmE9TLmPhWL71TtQZOOnRPs8ut6cSVcK+p1GAN1ztJhIBIU6X
before_build:
  - nuget restore ".\MobilePosemetre.sln"	
build:
  project: MobilePosemetre.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:""\PosemetreCore-Specs\bin\$env:CONFIGURATION\PosemetreCore-Specs.dll"" /noshadow" -filter:"+[PosemetreCore*]*" -output:opencoverCoverage.xml

    .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID